---
- name: Local Apt Ansible
  hosts: localhost
  connection: local
  become: true
  tasks:
   - name: apt install wget
     apt:
      name: wget
      state: present
   - name: apt install curl
     apt:
      name: curl
      state: present
   - name: apt  install htop
     apt:
      name: htop
      state: present

